sudo: false
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-dj18
    - python: 2.7
      env: TOXENV=py27-dj19
    - python: 3.5
      env: TOXENV=py35-dj18
    - python: 3.5
      env: TOXENV=py35-dj19
    - python: 2.7
      env: TOXENV=flake8
install:
  - pip install --upgrade pip tox
script:
  - tox
after_script:
  - cat .tox/$TOX_ENV/log/*.log
