sudo: false
language: python
matrix:
  include:
    # based on pip's .travis.yml
    - python: 2.6
      env: TOXENV=py26-dj13
    - python: 2.6
      env: TOXENV=py26-dj14
    - python: 2.7
      env: TOXENV=py27-dj14
    - python: 2.7
      env: TOXENV=py27-dj18
    - python: 3.3
      env: TOXENV=py33-dj18
    - python: 3.4
      env: TOXENV=py34-dj18
    - python: 2.7
      env: TOXENV=py27-dj18
    - python: 3.4
      env: TOXENV=py34-dj19
    - python: 3.5
      env: TOXENV=py35-dj19
install:
  - pip install --upgrade pip tox
script:
  - tox
after_script:
  - cat .tox/$TOX_ENV/log/*.log
