language: python
python:
  - "2.7"
  - "2.6"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_PACKAGE=Django>=1.8,<1.9
matrix:
  include:
    - python: "2.6"
      env: DJANGO_PACKAGE=Django==1.3.2
    - python: "2.6"
      env: DJANGO_PACKAGE=Django==1.4.5
    - python: "2.7"
      env: DJANGO_PACKAGE=Django==1.4.5
install:
  - pip install -q $DJANGO_PACKAGE --use-mirrors
  - pip install --use-mirrors .
script:
  - python setup.py test
